version: '3'
services:
  plant_akinator_db:
    container_name: plant_akinator_db
    build: ./db
    command: >
      --default-authentication-plugin=mysql_native_password &&
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: plant_akinator
      MYSQL_USER: sgi
      MYSQL_PASSWORD: sgi114
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: "Asia/Tokyo"
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

  plant_akinator_backend:
    container_name: plant_akinator_backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - plant_akinator_db
    environment:
      - DB_HOST=plant_akinator_db
      - DB_PORT=3306
      - DB_NAME=plant_akinator
      - DB_USER=sgi
      - DB_PASS=sgi114

  plant_akinator_phpmyadmin:
    container_name: plant_akinator_phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - plant_akinator_db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=plant_akinator_db
      - PMA_USER=sgi
      - PMA_PASSWORD=sgi114
    ports:
      - "8001:80"

  plant_akinator_frontend:
    container_name: plant_akinator_frontend
    build: ./frontend
    ports:
      - "80:4000"
    depends_on:
      - plant_akinator_backend

volumes:
  db-store:
