CREATE TABLE IF NOT EXISTS `plant_akinator`.`violas` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    classification VARCHAR(255),
    basic_specie VARCHAR(255),
    mutation VARCHAR(255),
    alias VARCHAR(255),
    origin VARCHAR(255),
    foreign_generic_name VARCHAR(255),
    stem_morphology VARCHAR(255),
    distribution_japan VARCHAR(255),
    distribution_foreign VARCHAR(255),
    distribution_supplement VARCHAR(255),
    flower_shape VARCHAR(255),
    flower_color VARCHAR(255),
    flower_distance VARCHAR(255),
    flower_season VARCHAR(255),
    flower_style VARCHAR(255),
    flower_supplement VARCHAR(255),
    leaf_shape VARCHAR(255),
    leaf_color VARCHAR(255),
    leaf_supplement VARCHAR(255),
    seed_shape VARCHAR(255),
    seed_color VARCHAR(255),
    seed_supplement VARCHAR(255),
    root_features VARCHAR(255),
    endangered_species VARCHAR(255),
    reference_sample VARCHAR(255),
    description TEXT
);